Aledutron
SPPU 2019 TE DSBDA Lab
SPPU Computer Engineering Third Year (TE) Data Science and Big Data Analysis (DSBDA) Lab Assignments (2019 Pattern)
Youtube DSBDA Lab Playlist Link: https://www.youtube.com/playlist?list=PLlShVH4JA0otdEk1LKPX_H6Cp5CblDq91

Problem Statement:
Group-A/Q3.ipynb

Descriptive Statistics - Measures of Central Tendency and variability
Perform the following operations on any open source dataset (e.g., data.csv)
1. Provide summary statistics (mean, median, minimum, maximum, standard deviation) for 
a dataset (age, income etc.) with numeric variables grouped by one of the qualitative 
(categorical) variable. For example, if your categorical variable is age groups and 
quantitative variable is income, then provide summary statistics of income grouped by the 
age groups. Create a list that contains a numeric value for each response to the categorical 
variable. 
2. Write a Python program to display some basic statistical details like percentile, mean, 
standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’ 
of iris.csv dataset.
Provide the codes with outputs and explain everything that you do in this step.

Explaination Video Link: https://www.youtube.com/watch?v=sUBNf72wRGY&list=PLlShVH4JA0otdEk1LKPX_H6Cp5CblDq91&index=1&pp=iAQB

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/Iris.csv")

In [3]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [4]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [5]:
df["SepalLengthCm"].describe()

count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000
Name: SepalLengthCm, dtype: float64

In [7]:
df.groupby("Species").describe().sum()

Id             count    150.000000
               mean     226.500000
               std       43.732139
               min      153.000000
               25%      189.750000
               50%      226.500000
               75%      263.250000
               max      300.000000
SepalLengthCm  count    150.000000
               mean      17.530000
               std        1.504540
               min       14.100000
               25%       16.625000
               50%       17.400000
               75%       18.400000
               max       20.700000
SepalWidthCm   count    150.000000
               mean       9.162000
               std        1.017319
               min        6.500000
               25%        8.450000
               50%        9.200000
               75%        9.850000
               max       11.600000
PetalLengthCm  count    150.000000
               mean      11.276000
               std        1.195317
               min        8.500000
               25%       10.500000
               50%       11.400000
               75%       12.050000
               max       13.900000
PetalWidthCm   count    150.000000
               mean       3.596000
               std        0.579612
               min        2.500000
               25%        3.200000
               50%        3.500000
               75%        4.100000
               max        4.900000
dtype: float64